apiVersion: v1
kind: Pod
metadata:
  name: selective-pod
spec:
  containers:
  - name: selective-container
    image: busybox
    command: ["sh", "-c", "echo Color=$COLOR && echo Port=$PORT && sleep 3600"]
    env:
    - name: COLOR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_PORT
