apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - name: db-container
    image: busybox
    command: ["sh", "-c", "echo User=$DB_USER && echo DB=$DB_NAME && sleep 3600"]
    envFrom:
    - secretRef:
        name: db-secret
