apiVersion: v1
kind: Pod
metadata:
  name: fullapp-pod
spec:
  containers:
  - name: fullapp-container
    image: busybox
    command: ["sh", "-c", "env | grep -E 'APP|DB' && sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: db-secret
